server:
  port: 8087
  address: 0.0.0.0
  tomcat:
    max-threads: 10

spring:
  redis:
    host: 127.0.0.1
    port: 7000
    timeout: 10000
    pool:
      max-idle: 300
      max-total: 600
      max-wait: 1000
      block-when-exhausted: true
      min-idle: 10
  application:
      name: wx-school

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.246:3306/gemini_bet?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: caiqiu
    password: Caiqiu502

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.wx.entity
